version: 2
updates:
  - package-ecosystem: pip
    directory: /authn-service/
    assignees:
      - kyle-boxboat
    reviewers:
      - dkoch84
    labels:
      - triage-required
    schedule:
      interval: "daily"
